use_frameworks!

platform :ios, '8.0'

target 'mjtestspec_Example' do
  pod 'mjtestspec', :path => '../'

  target 'mjtestspec_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
